### ISSUE TITLE
Layout improvement suggestions

### ISSUE THREAD

**Issue by areful** [b-brebion/android-mnist-digits-recognition#3]
Maybe the code below can offer better experience in fragment_draw.xml?

...

    <com.example.mnist_digits_recognition.DrawView
        android:id="@+id/drawView"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_marginTop="40dp"
        android:adjustViewBounds="true"
        android:background="@color/colorPrimaryDark"
        android:contentDescription="@string/drawing_area"
        app:layout_constraintDimensionRatio="1:1"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

...

**Comment by b-brebion** [comment]
Hi areful, first of all thanks for your interest in my work!
This is indeed a great idea to improve the layout of the application. I precisely plan to work on the responsive design in the next big version of the app, so your suggestion will be very useful as a starting point.

I will leave this issue open, so do not hesitate if you have other tips to help me enhance the layout of the app!

**Comment by b-brebion** [comment]
Closing since #4 corrected all major layout problems.
